#' @title Visualization of Taxonomic Re-mapping Results
#' @description This script processes re-mapping alignment counts and NCBI sequence reports
#' to visualize read distribution across nuclear and organellar genomes.
#' @author Josefine Weiss
#' @date 2024

library(tidyverse)
library(fs)

# --- 1. CONFIGURATION & PATHS ---
# Define directory paths for input data
# Note for GitHub: Use relative paths or environment variables for reproducibility
report_path <- "/Users/josefineweiss/Downloads/REMAPPING_sequence_reports/"
sample_path <- "/Users/josefineweiss/Desktop/Zijuan Manuscript/BTOKO_remapping" 

# List relevant files
report_files <- list.files(path = report_path, pattern = "_sequence_report.tsv", full.names = TRUE)
sample_files <- list.files(path = sample_path, pattern = "\\.tsv$", full.names = TRUE)

# --- 2. DATA LOAD FUNCTIONS ---

#' Load NCBI Sequence Reports
#' Parses assembly reports to map Accession IDs to human-readable chromosome names.
read_report_robust <- function(file) {
  read_tsv(file, comment = "#", show_col_types = FALSE,
           col_types = cols(
             `Chromosome name` = col_character(),
             `Sequence name` = col_character(),
             `GenBank seq accession` = col_character(),
             `RefSeq seq accession` = col_character(),
             `Assembly Accession` = col_character(),
             .default = col_guess()
           )) %>%
    select(
      assembly_acc = `Assembly Accession`, 
      chromosome_name = `Chromosome name`, 
      genbank_acc = `GenBank seq accession`, 
      refseq_acc = `RefSeq seq accession`
    ) %>%
    mutate(across(everything(), as.character))
}

#' Load Re-mapping Alignment Samples
#' Reads the alignment counts generated by the bioinformatic pipeline.
read_sample_robust <- function(file) {
  read_tsv(file, show_col_types = FALSE,
           col_types = cols(
             reference_id = col_character(),
             sample = col_character(),
             organism = col_character(),
             ref_genome = col_character(), 
             .default = col_guess()
           ))
}

# --- 3. DATA PROCESSING ---

# Load all reports and create a mapping table
all_reports <- map_dfr(report_files, read_report_robust)

# Create lookup table for accession IDs to chromosome names
mapping_table <- all_reports %>%
  pivot_longer(cols = c(genbank_acc, refseq_acc), 
               names_to = "source", 
               values_to = "accession_id") %>%
  filter(!is.na(accession_id)) %>%
  select(accession_id, chromosome_name, assembly_acc) %>%
  distinct()

# Load all alignment data
all_samples <- map_dfr(sample_files, read_sample_robust)

# Generate sample metadata overview
sample_overview <- all_samples %>%
  select(sample, organism, ref_genome) %>%
  distinct()

# Extract structural information from assembly reports
assembly_structure <- all_reports %>%
  select(ref_genome = assembly_acc, chromosome_name) %>%
  distinct()

# Create biological skeleton (Join samples with expected genomic structure)
skeleton <- left_join(sample_overview, assembly_structure, by = "ref_genome")

if(nrow(skeleton) == 0) {
  stop("Mapping Error: Skeleton is empty. Ensure Assembly Accessions in reports match input samples.")
}

# Map alignment IDs to chromosome names and handle missing data
real_data <- all_samples %>%
  left_join(mapping_table, by = c("reference_id" = "accession_id")) %>%
  select(sample, organism, chromosome_name, alignments) %>%
  filter(!is.na(chromosome_name))

# Final data merge and genomic categorization
final_plot_data <- skeleton %>%
  left_join(real_data, by = c("sample", "organism", "chromosome_name")) %>%
  mutate(alignments = replace_na(alignments, 0)) %>%
  mutate(
    seq_type = case_when(
      chromosome_name %in% c("MT", "Mt", "Mitochondrion", "MT1", "MT2") ~ "Mitochondria",
      str_detect(chromosome_name, "Pltd|Plstd|Chloro") ~ "Plastid",
      TRUE ~ "Nuclear"
    )
  ) %>%
  filter(!is.na(chromosome_name))

# Optional: Subset for specific taxa of interest
taxa_of_interest <- c("Dryas", "Leporidae", "Salmonidae", "Salicaceae")
subset_data <- final_plot_data %>%
  filter(organism %in% taxa_of_interest)

# --- 4. VISUALIZATION ---

# Create comparative bar chart
distribution_plot <- ggplot(final_plot_data, aes(x = chromosome_name, y = alignments, fill = seq_type)) +
  geom_col() +
  scale_fill_manual(values = c("Mitochondria" = "firebrick", 
                               "Plastid" = "forestgreen", 
                               "Nuclear" = "grey80")) +
  facet_wrap(~ organism, scales = "free") + 
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 6),
    legend.position = "top",
    strip.background = element_rect(fill = "white"),
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "Genomic Distribution of Re-mapped Reads",
    subtitle = "Categorization by Nuclear and Organellar Origin",
    x = "Genomic Scaffold / Organelle",
    y = "Read Count (Alignments)",
    fill = "Genomic Origin"
  )

# Save output as publication-quality PDF
ggsave("remapping_distribution_analysis.pdf", distribution_plot, width = 10, height = 7)

# Print completion status
message("Analysis complete. Results saved to 'remapping_distribution_analysis.pdf'.")
